project:
  type: book
  output-dir: docs/

book:
  title: "Normalisation pipeline"
  author: "Andreas G. Damsbo"
  favicon: "/images/favicon.png"
  date: last-modified
  search: true
  repo-url: https://github.com/agdamsbo/normalisation-pipeline/
  repo-actions: [edit]
  site-url: https://agdamsbo.github.io/normalisation-pipeline/
  page-navigation: true
  chapters:
    - index.qmd
    - 01-content.qmd
    - part: "Processing raw MRI data"
      chapters: 
        - 02-getting-started.qmd
        - 03-qc.qmd
    - part: "Finding Nemo"
      chapters: 
        - 04-finding-nemo.qmd
        - 05-nemo-data.qmd
  appendices: 
    - references.qmd

bibliography: references.bib

execute:
  echo: true
  freeze: auto

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
  pdf:
    documentclass: scrreprt

theme:
  light: cosmo
  dark: superhero
  
editor: source

author:
  - name: Andreas Gammelgaard Damsbo
    orcid: 0000-0002-7559-1154
    email: andrlr@rm.dk
    url: https://pure.au.dk/portal/en/persons/andreas-gammelgaard-damsbo(e3c4afce-3eba-4456-8b8b-2fd90775c87a).html
    affiliations:
      - ref: bbl
      - ref: dsc
affiliations:
  - id: dsc
    name: Danish Stroke Centre, AUH
    department: Neurology
    city: Aarhus
    country: Denmark
    url: https://www.en.auh.dk/departments/danish-stroke-centre/
  - id: bbl
    name: Brain Behaviour Laboratory, UBC
    department: Department of Physiotherapy
    city: Vancouver
    region: British Colombia
    country: Canada
    url: https://brain.rehab.med.ubc.ca/