project:
  type: book
  output-dir: docs/

book:
  title: "Normalisation pipeline"
  author: "Andreas G. Damsbo"
  favicon: "/images/favicon.png"
  date: last-modified
  search: true
  repo-url: https://github.com/agdamsbo/normalisation-pipeline/
  repo-actions: [edit]
  site-url: https://agdamsbo.github.io/normalisation-pipeline/
  page-navigation: true
  chapters:
    - index.qmd
    - 01-content.qmd
    - 02-getting-started.qmd
    - 03-qc.qmd
    - part: "Use case #1: Finding NeMo"
      chapters: 
        - 04-lesion-reg.qmd
        - 05-nemo-file-prep.qmd
        - 06-nemo-data.qmd
  appendices: 
    # - references.qmd
    - NEWS.md

citation:
  url: https://agdamsbo.github.io/normalisation-pipeline/
  type: book
bibliography: references.bib

execute:
  echo: true
  freeze: auto

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
  pdf:
    documentclass: scrreprt

theme:
  light: cosmo
  dark: superhero
  
editor: source

author:
  - name: Andreas Gammelgaard Damsbo
    orcid: 0000-0002-7559-1154
    email: andrlr@rm.dk
    url: https://pure.au.dk/portal/en/persons/andreas-gammelgaard-damsbo(e3c4afce-3eba-4456-8b8b-2fd90775c87a).html
    affiliations:
      - ref: bbl
      - ref: dsc
    roles: [conceptualization, methodology, software]
  - name: Christina Rubino
    affiliation:
      - ref: bbl
    roles: [data curation, validation, conceptualization]
affiliations:
  - id: dsc
    name: Danish Stroke Centre, AUH
    department: Neurology
    city: Aarhus
    country: Denmark
    url: https://www.en.auh.dk/departments/danish-stroke-centre/
  - id: bbl
    name: Brain Behaviour Laboratory, UBC
    department: Department of Physiotherapy
    city: Vancouver
    region: British Colombia
    country: Canada
    url: https://brain.rehab.med.ubc.ca/