on:
  push:
    branches: main
  #   
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
name: Render and Publish

jobs:
 build-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository
       uses: actions/checkout@v3

     - name: Set up Quarto
       uses: quarto-dev/quarto-actions/setup@v2
       with:
         # To install LaTeX to build PDF book
         tinytex: false
         # uncomment below and fill to pin a version
         # version: SPECIFIC-QUARTO-VERSION-HERE
      
     # - uses: r-lib/actions/setup-r@v2
     # - uses: r-lib/actions/setup-r-dependencies@v2
     #   with:
     #     packages:
     #     # any::knitr
     #       any::rmarkdown

     - name: Render Site
       uses: quarto-dev/quarto-actions/render@v2
       with:
         to: html

     - name: Setup Pages
       uses: actions/configure-pages@v3
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v1
       with:
       #   # Upload entire repository
         path: 'docs/'
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v2

